# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkproposal',
            options={'verbose_name': 'Propuesta de charla/taller', 'verbose_name_plural': 'Propuestas de charlas/talleres'},
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, b'Principiante'), (3, b'Intermedia'), (2, b'Avanzada')]),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text=b'Al enviar tu propuesta, le est\xc3\xa1s dando permiso a los organizadores de la conferencia para grabar, editar y transmitir audio y/o video de tu presentaci\xc3\xb3n. Si no estas de acuerdo con esto, no chequees este recuadro.'),
        ),
    ]
