# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Como te gustar\xeda que se imprima en tu gafete.(si quer\xe9s puede ser un nick)', max_length=100, verbose_name='Nombre completo o nick')),
                ('annotation', models.TextField(help_text='Si ten\xe9s alguna necesidadespecial que necesites quecontemplemos, contanos y haremoslo posible por ayudarte. Record\xe1que pod\xe9s reservar tus viandas para elevento. Segu\xed el link al principio de lap\xe1gina.', verbose_name='Observaciones')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, upload_to='attendees_cvs', verbose_name='Curriculum vitae')),
                ('show_to_sponsor', models.BooleanField(help_text='Acepto que mis datospersonales se compartan con los sponsors')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['full_name'],
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
    ]
