# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='annotation',
            field=models.TextField(help_text='Si ten\xe9s alguna necesidad especial que necesites que contemplemos, contanos y haremos lo posible por ayudarte. Record\xe1 que pod\xe9s reservar tus viandas para el evento. Segu\xed el link al principio de la p\xe1gina.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='show_to_sponsor',
            field=models.BooleanField(help_text='Acepto que mis datos personales se compartan con los sponsors', verbose_name='Compartir mis datos personales'),
        ),
    ]
