# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_auto_20161010_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='annotation',
            field=models.TextField(blank=True, help_text='Si ten\xe9s alguna necesidad especial que necesites que contemplemos, contanos y haremos lo posible por ayudarte. Record\xe1 que pod\xe9s reservar tus viandas para el evento. Segu\xed el link al principio de la p\xe1gina.', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
