# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_auto_20161010_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='annotation',
            field=models.TextField(blank=True, help_text='Si ten\xe9s alguna necesidad particular que necesites que contemplemos para el evento contanos y haremos lo posible por ayudarte. Te recomendamos reservar tu vianda para los d\xedas s\xe1bado y domingo, ya que cerca del complejo las ofertas gastron\xf3micas son reducidas Podr\xe1s elegir el tipo de vianda de acuerdo a tus necesidades. Encontrar\xe1s el link para hacerlo al confirmar la registraci\xf3n.', null=True, verbose_name='Observaciones'),
        ),
    ]
