# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 22:59
from __future__ import unicode_literals

from datetime import date, time

from django.db import migrations
from symposion.schedule.models import (Day, Room, Schedule, Section, Slot,
                                       SlotKind, SlotRoom)


def create_slot(day, kind, start, end, rooms):
    """Create slots for pycon."""
    slot = Slot.objects.create(day=day, kind=kind, start=start, end=end)
    for room in rooms:
        SlotRoom.objects.create(slot=slot, room=room)

    # Must save twice as the room attaches to the Slot name when save.
    # (default overriden behavior)
    slot.save()


def generate_schedules(*args, **kwargs):
    emprendedores = Section.objects.filter()[0]
    emprendedores.name = u'Club de emprendedores / Salón Fundadores UNS'
    emprendedores.save()
    palihue = Section.objects.filter()[1]
    palihue.name = u'Complejo Palihue UNS'
    palihue.save()

    schedule_emp = Schedule.objects.create(section=emprendedores)
    schedule_pal = Schedule.objects.create(section=palihue)

    dia_25 = Day.objects.create(schedule=schedule_emp, date=date(2016,11,25))
    dia_26 = Day.objects.create(schedule=schedule_pal, date=date(2016,11,26))
    dia_27 = Day.objects.create(schedule=schedule_pal, date=date(2016,11,27))


    charla_emp = SlotKind.objects.create(schedule=schedule_emp,label='charla')
    sprint_emp = SlotKind.objects.create(schedule=schedule_emp,label='sprints')
    taller_emp = SlotKind.objects.create(schedule=schedule_emp,label='taller')
    almuerzo_emp = SlotKind.objects.create(schedule=schedule_emp, label='almuerzo')
    acreditaciones_emp = SlotKind.objects.create(schedule=schedule_emp, label='acreditaciones')

    charla = SlotKind.objects.create(schedule=schedule_pal, label='charla')
    taller = SlotKind.objects.create(schedule=schedule_pal, label='taller')
    coffee = SlotKind.objects.create(schedule=schedule_pal, label='coffee-break')
    almuerzo = SlotKind.objects.create(schedule=schedule_pal, label='almuerzo')
    plenaria = SlotKind.objects.create(schedule=schedule_pal, label='plenaria')
    lightning = SlotKind.objects.create(schedule=schedule_pal, label='lightning')
    apertura = SlotKind.objects.create(schedule=schedule_pal, label='apertura')
    acreditaciones = SlotKind.objects.create(schedule=schedule_pal, label='acreditaciones')
    cierre = SlotKind.objects.create(schedule=schedule_pal, label='cierre')



    aula_emp_auditorio = Room.objects.create(name='auditorio', order=1, schedule=schedule_emp)
    aula_emp_azul = Room.objects.create(name='sala azul', order=2, schedule=schedule_emp)
    aula_emp_verde = Room.objects.create(name='sala verde', order=3, schedule=schedule_emp)
    aula_fund = Room.objects.create(name='fundadores', order=4, schedule=schedule_emp)

    aula_1_pal = Room.objects.create(name='aula_1', order=1, schedule=schedule_pal)
    aula_2_pal = Room.objects.create(name='aula_2', order=2, schedule=schedule_pal)
    aula_3_pal = Room.objects.create(name='aula_3', order=3, schedule=schedule_pal)
    aula_4_pal = Room.objects.create(name='aula_4', order=4, schedule=schedule_pal)


    # Viernes
    create_slot(dia_25, taller_emp, time(8,0),time(19,0), (aula_fund,))
    create_slot(dia_25, acreditaciones_emp, time(8,30),time(9,0), (aula_emp_azul,
                                                                   aula_emp_verde,
                                                                   aula_emp_auditorio))

    create_slot(dia_25, charla_emp, time(9,0),time(10,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(10,0),time(11,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(11,0),time(12,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(13,0),time(14,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(14,0),time(15,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(15,0),time(16,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(16,0),time(17,0), (aula_emp_auditorio,))
    create_slot(dia_25, charla_emp, time(17,0),time(18,0), (aula_emp_auditorio,))

    create_slot(dia_25, sprint_emp, time(9,0),time(12,0), (aula_emp_azul,))
    create_slot(dia_25, sprint_emp, time(13,0),time(18,0), (aula_emp_azul,))
    create_slot(dia_25, sprint_emp, time(9,0),time(12,0), (aula_emp_verde,))
    create_slot(dia_25, sprint_emp, time(13,0),time(18,0), (aula_emp_verde,))


    create_slot(dia_25, almuerzo_emp, time(12,0),time(13,0), (aula_emp_azul,
                                                              aula_emp_verde,
                                                              aula_emp_auditorio))


    # Sabado
    create_slot(dia_26, acreditaciones, time(9,0),time(9,30), (aula_1_pal,
                                                               aula_2_pal,
                                                               aula_3_pal,
                                                               aula_4_pal))


    # Aula 1
    create_slot(dia_26, apertura, time(9,30),time(10,0), (aula_1_pal,))

    create_slot(dia_26, charla, time(10,0),time(11,0), (aula_1_pal,))
    create_slot(dia_26, charla, time(11,0),time(12,0), (aula_1_pal,))
    create_slot(dia_26, charla, time(12,0),time(13,0), (aula_1_pal,))

    create_slot(dia_26, charla, time(14,0),time(15,0), (aula_1_pal,))
    create_slot(dia_26, charla, time(15,0),time(16,0), (aula_1_pal,))
    create_slot(dia_26, charla, time(16,0),time(17,0), (aula_1_pal,))

    create_slot(dia_26, charla, time(17,30),time(18,30), (aula_1_pal,))
    create_slot(dia_26, charla, time(18,30),time(19,30), (aula_1_pal,))


    #Aula 2

    create_slot(dia_26, charla, time(10,0),time(11,0), (aula_2_pal,))
    create_slot(dia_26, charla, time(11,0),time(12,0), (aula_2_pal,))
    create_slot(dia_26, charla, time(12,0),time(13,0), (aula_2_pal,))

    create_slot(dia_26, charla, time(15,0),time(16,0), (aula_2_pal,))
    create_slot(dia_26, charla, time(16,0),time(17,0), (aula_2_pal,))


    # Taller 1
    create_slot(dia_26, taller, time(10,0),time(13,0), (aula_3_pal,))
    create_slot(dia_26, taller, time(14,0),time(15,30), (aula_3_pal,))
    create_slot(dia_26, taller, time(15,30),time(17,0), (aula_3_pal,))


    # Taller 2
    create_slot(dia_26, taller, time(10,0),time(11,0), (aula_4_pal,))
    create_slot(dia_26, taller, time(11,0),time(13,0), (aula_4_pal,))
    create_slot(dia_26, taller, time(14,0),time(17,0), (aula_4_pal,))

    # Almuerzo
    create_slot(dia_26, almuerzo, time(13,0),time(14,0), (aula_1_pal,
                                                          aula_2_pal,
                                                          aula_3_pal,
                                                          aula_4_pal))

    # Merienda
    create_slot(dia_26, coffee, time(17,0),time(17,30), (aula_1_pal,
                                                         aula_2_pal,
                                                         aula_3_pal,
                                                         aula_4_pal))


    #Domingo

    # Aula 1

    create_slot(dia_27, charla, time(10,0),time(11,0), (aula_1_pal,))
    create_slot(dia_27, charla, time(11,0),time(12,0), (aula_1_pal,))
    create_slot(dia_27, charla, time(12,0),time(13,0), (aula_1_pal,))

    create_slot(dia_27, charla, time(14,0),time(15,0), (aula_1_pal,))
    create_slot(dia_27, charla, time(15,0),time(16,0), (aula_1_pal,))

    create_slot(dia_27, charla, time(16,30),time(17,30), (aula_1_pal,))
    create_slot(dia_27, charla, time(17,30),time(18,30), (aula_1_pal,))
    create_slot(dia_27, charla, time(18,30),time(19,0), (aula_1_pal,))

    #Aula 2

    create_slot(dia_27, charla, time(10,0),time(11,0), (aula_2_pal,))
    create_slot(dia_27, charla, time(11,0),time(12,0), (aula_2_pal,))
    create_slot(dia_27, charla, time(12,0),time(13,0), (aula_2_pal,))

    create_slot(dia_27, charla, time(14,0),time(15,0), (aula_2_pal,))
    create_slot(dia_27, charla, time(15,0),time(16,0), (aula_2_pal,))


    # Taller 1
    create_slot(dia_27, taller, time(10,0),time(13,0), (aula_3_pal,))
    create_slot(dia_27, taller, time(14,0),time(16,0), (aula_3_pal,))


    # Taller 2
    create_slot(dia_27, taller, time(10,0),time(13,0), (aula_4_pal,))

    create_slot(dia_27, charla, time(14,0),time(15,0), (aula_4_pal,))
    create_slot(dia_27, charla, time(15,0),time(16,0), (aula_4_pal,))

    # Almuerzo
    create_slot(dia_27, almuerzo, time(13,0),time(14,0), (aula_1_pal,
                                                          aula_2_pal,
                                                          aula_3_pal,
                                                          aula_4_pal))

    # Merienda
    create_slot(dia_27, coffee, time(16,0),time(16,30), (aula_1_pal,
                                                         aula_2_pal,
                                                         aula_3_pal,
                                                         aula_4_pal))


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_auto_20161021_1839'),
    ]

    operations = [migrations.RunPython(generate_schedules)
    ]
